[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.21"

[features]
resolution = true
skip-lint = false

[programs.localnet]
jupiter_delegate = "JPDGXJky3iRkPmJx3cixg5cxJGGwP9kXBJzMpT5GLir"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
create-lookup-table = "yarn run ts-node app/create-lookup-table.ts"
extend-lookup-table = "yarn run ts-node app/extend-lookup-table.ts"
grant-access = "yarn run ts-node app/grant-access.ts"
fetch-config = "yarn run ts-node app/fetch-config.ts"
init-config = "yarn run ts-node app/init-config.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
trade = "yarn run ts-node app/trade.ts"
ultra = "yarn run ts-node app/ultra.ts"
modify-cooldown-duration = "yarn run ts-node app/modify-cooldown-duration.ts"

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "tests/genesis/token.so"

[[test.genesis]]
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
program = "tests/genesis/jupiter.so"

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "./tests/accounts/usdc.json"

[[test.validator.account]]
address = "So11111111111111111111111111111111111111112"
filename = "./tests/accounts/wsol.json"
