[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.5"

[features]
resolution = true
skip-lint = false

[programs.localnet]
jupiter_delegate = "99wACTD1Eoifq2FtTvRvC6Etk1bwcZF19BuvGC1W6Tjm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
trade = "yarn run ts-node app/trade.ts"

[test]
startup_wait = 60000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "tests/genesis/token.so"

[[test.genesis]]
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
program = "tests/genesis/jupiter.so"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "./tests/accounts/usdc.json"

[[test.validator.account]]
address = "So11111111111111111111111111111111111111112"
filename = "./tests/accounts/wsol.json"